### ISSUE TITLE
pip install seems to be broken

### ISSUE THREAD

**Issue by verdverm** [hofstadter-io/self-driving-desktop#13]

**Comment by verdverm** [comment]
@philipdexter fyi

**Comment by philipdexter** [comment]
I reuploaded and it seems to work now.

**Comment by verdverm** [comment]
any idea on what went wrong? did I upload incorrectly last time?

**Comment by philipdexter** [comment]
I'm really not sure, since even when I uploaded I didn't initially get it
to work. Starting with a `make clean` might fix it.
