### ISSUE TITLE
What would one use this for?

### ISSUE THREAD

**Issue by squiig** [hofstadter-io/self-driving-desktop#15]
It's cool, but I can't think of example use cases.

**Comment by verdverm** [comment]
I'm currently using it to drive the mouse and keyboard during demo video recording. In this way, the video will not need to be edited, and I can update small parts when docs / ops change, and then kick off a new full recording, or just edit the new section into place.

Another use case would be copying data from one program to another. There are a lot of non-tech companies which have archaic systems that require the same info being input into several applications.

We plan to add capabilities to specify a data file and use that during playback.

Really anything you don't want to have to use the mouse/keyboard for over and over. Or where you want consistent precision, like demo making.
