### ISSUE TITLE
sdd playlist.txt error

### ISSUE THREAD

**Issue by langxj** [hofstadter-io/self-driving-desktop#16]
![image](https://user-images.githubusercontent.com/7477494/59007516-46a20180-8859-11e9-8813-45d262f8e4a5.png)

**Comment by verdverm** [comment]
This project only supports Linux at the current time. We are using a XLib library which is only available on Linux.

To "fix" this issue "easily," we could add some OS checks around the XLib portions, which would effectively turn off features on a specific OS. We could then add in libraries for those platforms to get the same functionality.

Unfortunately, I don't have a windows system to dev/test on.

**Comment by verdverm** [comment]
#3 for further discussions

**Comment by mushroomlb** [comment]
When to support windows
